import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <main className="flex flex-col p-8 items-center justify-center bg-gray-800 w-full">
            {children}
          </main>
        </body>
      </Provider>
    </html>
  );
}
